import axios from 'axios';
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import Add from '../Components/AddButton/Add';
import AddButton from '../Components/AddButton/AddButton';
import Featured from '../Components/Featured/Featured';
import PizzaList from '../Components/Pizza List/PizzaList';
import styles from '../styles/Home.module.css';

export default function Home({ pizzaList, admin }) {
    const [close, setClose] = useState(true);

    return (
        <div className={styles.container}>
            <Head>
                <title>Pizza Restaurant</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Featured />
            {admin && <AddButton setClose={setClose} />}
            <PizzaList pizzaList={pizzaList} />
            {!close && <Add setClose={setClose} />}
        </div>
    );
}

export const getServerSideProps = async (ctx) => {
    const myCookie = ctx.req?.cookies || '';
    let admin = false;

    if (myCookie.token === process.env.TOKEN) {
        admin = true;
    }

    const res = await axios.get('http://localhost:3000/api/products');
    return {
        props: {
            pizzaList: res.data,
            admin,
        },
    };
};
